[project]
name = "bin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "hvac>=2.4.0",
  "typer>=0.21.0",
]

[tool.ruff.lint]
ignore = ["E402"]
