---
notARepository: skip
quitOnTopLevelReturn: true
gui:
  showBottomLine: false
  showRandomTip: false
  nerdFontsVersion: "3"
  filterMode: fuzzy
  skipDiscardChangeWarning: true
  border: rounded
  theme:
    activeBorderColor:
      - "#268bd2"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
git:
  overrideGpg: true
  pagers:
    - pager: >
        delta --paging=never --hyperlinks
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  commit:
    signOff: true
  parseEmoji: false
update:
  method: never
os:
  editPreset: nvim
  editInTerminal: true
promptToReturnFromSubprocess: false
customCommands:
  - key: "R"
    context: "files"
    description: "Re-add all things changed in tracked dotfiles"
    command: "chezmoi re-add"
